pro_lang/home/urls.py
from django.urls import path
from . import views
from language.views import desp_home

urlpatterns = [
    path('', views.index, name="index"),
    path('<int:pk>/', views.detail_page, name="detail"),
    path('search/', views.search, name="search"),
]

pro_lang/language/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.desp_home, name='description_home'),
]

pro_lang/pro_lang/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('description/', include('language.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

pro_lang/home/models.py
from django.db import models

from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.


class HomeLanguage(models.Model):
    name = models.CharField(max_length=500)
    diff_level = models.IntegerField(
        default=1,
        validators=[MaxValueValidator(5), MinValueValidator(1)]
    )

    def __str__(self):
        return f'{self.name}'

pro_lang/language/models.py
from django.db import models
from home.models import HomeLanguage

# Create your models here.


class Description(models.Model):
    name = models.ForeignKey(HomeLanguage, default=None,
                             on_delete=models.CASCADE)
    url_link = models.URLField(max_length=1000)
    image = models.ImageField(upload_to='images/')
    desp = models.TextField()
    salary = models.IntegerField()

    def __str__(self):
        return f'{str(self.name)} + {self.salary}'

pro_lang/home/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import HomeLanguage
from language.models import Description
from django.contrib import messages
from django.db.models import Q
# Create your views here.
from django.http import Http404


def index(request):
    data = HomeLanguage.objects.all()
    context = {
        'data': data
    }
    return render(request, 'home/content.html', context)


def search(request):
    if request.method == 'POST':
        search_bar = request.POST['search']
        print(search_bar)
        search_content = search_bar.title()
        if search_content:
            matching = HomeLanguage.objects.filter(
                Q(name__icontains=search_content))
            if matching:
                return render(request, 'home/content.html', {'search_result': matching})
            else:
                messages.warning(request, 'Not Found')
                return redirect('index')
        else:
            messages.warning(request, 'Not Found')
            return redirect('index')
    return render(request, 'home/content.html')


def detail_page(request, pk):

    instance = get_object_or_404(HomeLanguage,
                                 pk=pk)
    print(instance.pk)
    context = {
        'instance': instance
    }

    return render(request, 'home/detail.html', context)

pro_lang/language/views.py
from django.shortcuts import render
from . models import Description
# Create your views here.


def desp_home(request):
    obj = Description.objects.all()

    context = {
        'objects': obj
    }
    return render(request, 'language/descriptive.html', context)

pro_lang/home/templates/home/code_languages.html
{% for allData in data %}

<a href="{% url 'detail' pk=allData.pk %}" class="text-decoration-none text-dark hover-link">
  {% if allData.diff_level == 1 %}
  <div class=" col mb-4" title="Very Easy">
    <div class="card h-100">
      <div class="card-img-top text-center bg-dark" style="height: 200px;">
        <h1 class="mt-5 text-white" style="font-size: 70px;">{{allData.name}}</h1>
      </div>
      <div class="card-body">
        <h3 class="card-title text-center text-bolder">Difficulty Level</h3><br>
        <p class="card-text text-center">
          <span class="rounded-circle box1-fill-green"></span>
          <span class="rounded-circle box1-green"></span>
          <span class="rounded-circle box1-green"></span>
          <span class="rounded-circle box1-green"></span>
          <span class="rounded-circle box1-green"></span>

        </p><br>
      </div>
    </div>
  </div>

  {% elif allData.diff_level == 2 %}
  <div class="col mb-4" title="Easy">
    <div class="card h-100">
      <div class="card-img-top text-center bg-dark" style="height: 200px;">
        <h1 class="mt-5 text-white" style="font-size: 70px;">{{allData.name}}</h1>
      </div>
      <div class="card-body">
        <h3 class="card-title text-center text-bolder">Difficulty Level</h3><br>
        <p class="card-text text-center">
          <span class="rounded-circle box1-fill-green"></span>
          <span class="rounded-circle box2-fill-lightgreen"></span>
          <span class="rounded-circle box1-green"></span>
          <span class="rounded-circle box1-green"></span>
          <span class="rounded-circle box1-green"></span>
        </p><br>
      </div>
    </div>
  </div>

  {% elif allData.diff_level == 3 %}
  <div class="col mb-4" title="Moderate">
    <div class="card h-100">
      <div class="card-img-top text-center bg-dark" style="height: 200px;">
        <h1 class="mt-5 text-white" style="font-size: 70px;">{{allData.name}}</h1>
      </div>
      <div class="card-body">
        <h3 class="card-title text-center text-bolder">Difficulty Level</h3><br>
        <p class="card-text text-center">
          <span class="rounded-circle box1-fill-green"></span>
          <span class="rounded-circle box2-fill-lightgreen"></span>
          <span class="rounded-circle box3-fill-yellow"></span>
          <span class="rounded-circle box1-green"></span>
          <span class="rounded-circle box1-green"></span>
        </p><br>
      </div>
    </div>
  </div>

  {% elif allData.diff_level == 4 %}
  <div class="col mb-4" title="Difficult">
    <div class="card h-100">
      <div class="card-img-top text-center bg-dark" style="height: 200px;">
        <h1 class="mt-5 text-white" style="font-size: 70px;">{{allData.name}}</h1>
      </div>
      <div class="card-body">
        <h3 class="card-title text-center text-bolder">Difficulty Level</h3><br>
        <p class="card-text text-center">
          <span class="rounded-circle box1-fill-green"></span>
          <span class="rounded-circle box2-fill-lightgreen"></span>
          <span class="rounded-circle box3-fill-yellow"></span>
          <span class="rounded-circle box4-fill-lightred"></span>
          <span class="rounded-circle box1-green"></span>
        </p><br>
      </div>
    </div>
  </div>

  {% elif allData.diff_level == 5 %}
  <div class="col mb-4" title="Very Difficult">
    <div class="card h-100">
      <div class="card-img-top text-center bg-dark" style="height: 200px;">
        <h1 class="mt-5 text-white" style="font-size: 70px;">{{allData.name}}</h1>
      </div>
      <div class="card-body">
        <h3 class="card-title text-center text-bolder">Difficulty Level</h3><br>
        <p class="card-text text-center">
          <span class="rounded-circle box1-fill-green"></span>
          <span class="rounded-circle box2-fill-lightgreen"></span>
          <span class="rounded-circle box3-fill-yellow"></span>
          <span class="rounded-circle box4-fill-lightred"></span>
          <span class="rounded-circle box5-fill-red"></span>
        </p><br>
      </div>
    </div>
  </div>

  {% else %}
  <div class="col mb-4" title="easy">
    <div class="card h-100">
      <div class="card-img-top text-center bg-dark" style="height: 200px;">
        <h1 class="mt-5 text-white" style="font-size: 70px;">{{allData.name}}</h1>
      </div>
      <div class="card-body">
        <h3 class="card-title text-center text-bolder">Difficulty Level</h3><br>
        <p class="card-text text-center">
          <i class="fa fa-html5" aria-hidden="true">Not Mention</i>
        </p><br>
      </div>
    </div>
  </div>
  {% endif %}

</a>
{% endfor %}

pro_lang/home/templates/home/content.html
{% extends 'home/layout.html' %}

{% block title %}
Programming Languages
{% endblock title %}

{% block content %}

<!-- cards-->
<div class="container mt-5">
  <div class="row row-cols-1 row-cols-md-2 row-cols-lg-2 row-cols-xl-3">
    {% include 'home/code_languages.html' %}
    {% if search_result is not None %}
    {% for data in search_result %}
    <a href="{% url 'detail' pk=data.pk %}" class="text-decoration-none text-dark hover-link">
      {% if data.diff_level == 1 %}
      <div class=" col mb-4" title="Very Easy">
        <div class="card h-100">
          <div class="card-img-top text-center bg-dark" style="height: 200px;">
            <h1 class="mt-5 text-white" style="font-size: 70px;">{{data.name}}</h1>
          </div>
          <div class="card-body">
            <h3 class="card-title text-center text-bolder">Difficulty Level</h3><br>
            <p class="card-text text-center">
              <span class="rounded-circle box1-fill-green"></span>
              <span class="rounded-circle box1-green"></span>
              <span class="rounded-circle box1-green"></span>
              <span class="rounded-circle box1-green"></span>
              <span class="rounded-circle box1-green"></span>

            </p><br>
          </div>
        </div>
      </div>

      {% elif data.diff_level == 2 %}
      <div class="col mb-4" title="Easy">
        <div class="card h-100">
          <div class="card-img-top text-center bg-dark" style="height: 200px;">
            <h1 class="mt-5 text-white" style="font-size: 70px;">{{data.name}}</h1>
          </div>
          <div class="card-body">
            <h3 class="card-title text-center text-bolder">Difficulty Level</h3><br>
            <p class="card-text text-center">
              <span class="rounded-circle box1-fill-green"></span>
              <span class="rounded-circle box2-fill-lightgreen"></span>
              <span class="rounded-circle box1-green"></span>
              <span class="rounded-circle box1-green"></span>
              <span class="rounded-circle box1-green"></span>
            </p><br>
          </div>
        </div>
      </div>

      {% elif data.diff_level == 3 %}
      <div class="col mb-4" title="Moderate">
        <div class="card h-100">
          <div class="card-img-top text-center bg-dark" style="height: 200px;">
            <h1 class="mt-5 text-white" style="font-size: 70px;">{{data.name}}</h1>
          </div>
          <div class="card-body">
            <h3 class="card-title text-center text-bolder">Difficulty Level</h3><br>
            <p class="card-text text-center">
              <span class="rounded-circle box1-fill-green"></span>
              <span class="rounded-circle box2-fill-lightgreen"></span>
              <span class="rounded-circle box3-fill-yellow"></span>
              <span class="rounded-circle box1-green"></span>
              <span class="rounded-circle box1-green"></span>
            </p><br>
          </div>
        </div>
      </div>

      {% elif data.diff_level == 4 %}
      <div class="col mb-4" title="Difficult">
        <div class="card h-100">
          <div class="card-img-top text-center bg-dark" style="height: 200px;">
            <h1 class="mt-5 text-white" style="font-size: 70px;">{{data.name}}</h1>
          </div>
          <div class="card-body">
            <h3 class="card-title text-center text-bolder">Difficulty Level</h3><br>
            <p class="card-text text-center">
              <span class="rounded-circle box1-fill-green"></span>
              <span class="rounded-circle box2-fill-lightgreen"></span>
              <span class="rounded-circle box3-fill-yellow"></span>
              <span class="rounded-circle box4-fill-lightred"></span>
              <span class="rounded-circle box1-green"></span>
            </p><br>
          </div>
        </div>
      </div>

      {% elif data.diff_level == 5 %}
      <div class="col mb-4" title="Very Difficult">
        <div class="card h-100">
          <div class="card-img-top text-center bg-dark" style="height: 200px;">
            <h1 class="mt-5 text-white" style="font-size: 70px;">{{data.name}}</h1>
          </div>
          <div class="card-body">
            <h3 class="card-title text-center text-bolder">Difficulty Level</h3><br>
            <p class="card-text text-center">
              <span class="rounded-circle box1-fill-green"></span>
              <span class="rounded-circle box2-fill-lightgreen"></span>
              <span class="rounded-circle box3-fill-yellow"></span>
              <span class="rounded-circle box4-fill-lightred"></span>
              <span class="rounded-circle box5-fill-red"></span>
            </p><br>
          </div>
        </div>
      </div>

      {% else %}
      <div class="col mb-4" title="easy">
        <div class="card h-100">
          <div class="card-img-top text-center bg-dark" style="height: 200px;">
            <h1 class="mt-5 text-white" style="font-size: 70px;">{{data.name}}</h1>
          </div>
          <div class="card-body">
            <h3 class="card-title text-center text-bolder">Difficulty Level</h3><br>
            <p class="card-text text-center">
              <i class="fa fa-html5" aria-hidden="true">Not Mention</i>
            </p><br>
          </div>
        </div>
      </div>
      {% endif %}

    </a>
    {% endfor %}

    {% else %}
    {% if messages %}
    <ul class="messages">
      {% for message in messages %}
      <script>alert('{{ message }}');</script>
      {% endfor %}
    </ul>
    {% endif %}

    {% endif %}

  </div>
</div>

{% endblock content %}

pro_lang/home/templates/home/detail.html
{% include "language/descriptive.html" %}

pro_lang/home/templates/home/layout.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="description" content="Programming Languages with their difficulty level and annual salary">
  <meta name="keywords"
    content="Programming, Languages, Languages to Learn, all Programming Languages, Programming Language with difficulty level, programming languages available">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="icon" type="image/ico" href="{% static 'home/images/title_logo.png' %}">
  <link rel="stylesheet" href="{% static 'home/css/style.css' %}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <title>
    {% block title %}

    {% endblock title %}</title>
</head>

<body>
  <!-- containes navigation bar settings  -->
  <header class="container sticky-top">
    <nav class="navbar navbar-expand-lg navbar-light bg-white borders">
      <a class="navbar-brand mx-auto" href="{% url 'index' %}">
        <img src="{% static 'home/images/logo.jpg' %}" width="300" height="50" alt="Home Logo">
      </a>
      {% block search %}
      {% include "home/search.html" %}
      {% endblock search %}
    </nav>
  </header>

  {% block content %}

  {% endblock content %}



  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
    crossorigin="anonymous"></script>
</body>

</html>

pro_lang/home/templates/home/search.html
{% block search %}
<div class="navbar-collapse" id="navbarSupportedContent">
  <form class="form-inline my-2 my-lg-0 ml-auto" method="post" action="{% url 'search' %}">
    {% csrf_token %}
    <input class="form-control mr-sm-2 mx-auto" type="search" name="search" placeholder="Search" aria-labe l="Search">
    <button class="btn btn-outline-success my-2 my-sm-0 mr-auto" onclick="myFunction()" type="submit">Search</button>
  </form>
</div>
{% endblock search %}

pro_lang/language/templates/language/descriptive.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="icon" type="image/ico" href="{% static 'home/images/title_logo.png' %}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'language/css/descriptive.css' %}" type="text/css">
  <title>{{instance.name}}</title>
</head>

<body>
  <div class="container mt-5 text-center">
    <a class="btn btn-success" href="{% url 'index' %}" role="button">Home</a>
    {% for datas in instance.description_set.all %}
    <div class="mt-5 card mb-3">

      <a href="{{datas.url_link}}" class="image-hover-zoom" target="_blank">
        <img src="{{datas.image.url}}" class="img-responsive" width="100%" height="100%" alt="{{datas.name}}">

      </a>

      <div class="card-body">
        <h5 class="card-title" style="text-align: left;"><ins>Description :-</ins></h5>
        <p class="card-text text-justify" style="text-indent: 50px;">{{datas.desp}}</p>

        <table class="table table-bordered col-sm-4 text-center">
          <thead>
            <tr>
              <th scope="col">Approx.</th>
              <th scope="col">Salary</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Annual Salary</td>
              <td>${{datas.salary}}</td>
            </tr>
          </tbody>
        </table>

        <p class=" card-text"><small class="text-muted">Thank You</small></p>
      </div>
    </div>
    {% endfor %}
  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
    crossorigin="anonymous"></script>
</body>

</html>